import { Sequence } from '.'
import { BACKPAR_C_W, BACKPAR_LR_A } from '../presets/backpar'
import { BEAMS_BLINK, BEAMS_WAVE } from '../presets/beams'
import { CL } from '../presets/cl'
import {
  COLOR_BLUE,
  COLOR_GREEN,
  COLOR_ORANGE,
  COLOR_PINK,
  COLOR_RAINBOW,
  COLOR_RED,
  COLOR_WHITE,
  COLOR_WHITE_MH,
  COLOR_YELLOW,
} from '../presets/colors'
import {
  FLOORPAR,
  FLOORPAR_RANDOM_BLINK,
  FLOORPAR_SINWAVE,
  FLOORPAR_WAVE,
} from '../presets/floorpar'
import { FS } from '../presets/fs'
import { GROUND_B } from '../presets/ground'
import { LED_BLINK, LED_ON } from '../presets/led'
import {
  MH_BLINK,
  MH_ON,
  MH_PAN_CENTER,
  MH_PAN_FOCUS,
  MH_POS_ROUND,
  MH_TILT_FL,
  MH_TILT_MID,
  MH_TILT_TOP,
  MH_TILT_WAVE,
} from '../presets/mh'
import { NAGARE_BLUE, NAGARE_PINK, NAGARE_W } from '../presets/nagare'
import { SPOT, SPOT_C, SPOT_L, SPOT_R } from '../presets/spot'
import { SS, SS_L, SS_R } from '../presets/ss'
import { MATTETE_LAST_FRAME } from './03_mattete'

export const omohito: Sequence[] = [
  {
    note: '思いよ一つになれ',
    steps: [
      {
        id: '歌詞始まり',
        position: 0,
        extends: [...MATTETE_LAST_FRAME],
      },
      {
        id: '↑',
        position: 0.1,
        fade: 1,
        extends: [
          FS,
          SS,
          COLOR_WHITE,
          LED_ON,
          MH_ON,
          BACKPAR_C_W,
          // prepare
          MH_PAN_CENTER,
          MH_TILT_MID,
        ],
      },
      {
        id: '↑（ひとつになる）',
        position: 1.1,
        fade: 5,
        extends: [
          FS,
          SS,
          COLOR_WHITE,
          LED_ON,
          MH_ON,
          MH_PAN_FOCUS,
          MH_TILT_FL,
          BACKPAR_C_W,
        ],
      },
      {
        id: '前奏ピアノ',
        position: 13.1,
        fade: 1,
        extends: [
          SS,
          COLOR_WHITE,
          LED_ON,
          // after
          MH_PAN_FOCUS,
          MH_TILT_TOP,
        ],
      },
      {
        id: '前奏上がる',
        position: 17.2,
        fade: 1,
        extends: [
          CL,
          FS,
          COLOR_WHITE,
          LED_ON,
          MH_POS_ROUND,
          MH_BLINK,
          BEAMS_WAVE,
        ],
      },
      {
        id: '1A',
        position: 26.5,
        fade: 1,
        extends: [CL, FS, COLOR_WHITE, LED_BLINK],
      },
      {
        id: '1B',
        position: 43,
        fade: 1,
        extends: [
          CL,
          FS,
          SS,
          COLOR_YELLOW,
          LED_BLINK,
          // prepare
          MH_PAN_CENTER,
          MH_TILT_TOP,
        ],
      },
      {
        id: 'サビ1',
        position: 1 * 60 + 1,
        fade: 2,
        extends: [
          // CL,
          FS,
          SS_L,
          NAGARE_BLUE,
          COLOR_BLUE,
          LED_ON,
          MH_PAN_CENTER,
          MH_TILT_TOP,
          MH_ON,
        ],
      },
      {
        id: 'サビ1上がる',
        position: 1 * 60 + 12.4,
        fade: 0,
        extends: [
          // CL,
          FS,
          SS_L,
          NAGARE_BLUE,
          COLOR_BLUE,
          LED_BLINK,
          MH_BLINK,
          MH_TILT_WAVE,
          BEAMS_WAVE,
        ],
      },
      {
        id: '2A',
        position: 1 * 60 + 35.6,
        fade: 1,
        extends: [
          // CL,
          FS,
          NAGARE_W,
          COLOR_WHITE,
          LED_BLINK,
        ],
      },
      {
        id: '2B',
        position: 1 * 60 + 49,
        fade: 1,
        extends: [
          // CL,
          FS,
          NAGARE_PINK,
          SS_R,
          COLOR_PINK,
          LED_BLINK,
          // prepare
          COLOR_WHITE_MH,
        ],
      },
      {
        id: 'サビ2',
        position: 2 * 60 + 6,
        fade: 1,
        extends: [
          // CL,
          FS,
          NAGARE_PINK,
          SS_R,
          COLOR_PINK,
          COLOR_WHITE_MH,
          LED_BLINK,
          MH_POS_ROUND,
          MH_ON,
          BEAMS_BLINK,
        ],
      },
      {
        id: '間奏1',
        position: 2 * 60 + 29,
        fade: 1,
        extends: [
          // CL,
          FS,
          NAGARE_PINK,
          SS_R,
          COLOR_GREEN,
          COLOR_WHITE_MH,
          LED_BLINK,
          MH_POS_ROUND,
          MH_ON,
          BEAMS_WAVE,
          FLOORPAR_WAVE,
        ],
      },
      {
        id: '間奏2',
        position: 2 * 60 + 52,
        fade: 1,
        extends: [
          // CL,
          SPOT,
          SS_R,
          COLOR_BLUE,
          COLOR_WHITE_MH,
          LED_BLINK,
          MH_POS_ROUND,
          MH_ON,
          BEAMS_WAVE,
          FLOORPAR_SINWAVE,
        ],
      },
      {
        id: 'C かけがえのない日々を',
        position: 3 * 60 + 3,
        fade: 1,
        extends: [
          // CL,
          // FS,
          SS,
          COLOR_BLUE,
          LED_ON,
          BACKPAR_C_W,
          SPOT_C,
          SPOT_L,
          SPOT_R,
        ],
      },
      {
        id: 'C かけがえのない日々を(2)',
        position: 3 * 60 + 15,
        fade: 1,
        extends: [
          // CL,
          FS,
          SS,
          COLOR_ORANGE,
          LED_ON,
          BACKPAR_C_W,
          BACKPAR_LR_A,
        ],
      },
      {
        id: 'C なにかに',
        position: 3 * 60 + 30,
        fade: 3,
        extends: [
          // CL,
          FS,
          SS,
          COLOR_ORANGE,
          LED_ON,
          BACKPAR_C_W,
          BACKPAR_LR_A,
          FLOORPAR,
          // prepare
          MH_POS_ROUND,
        ],
      },
      {
        id: 'ラスサビ',
        position: 3 * 60 + 40.5,
        fade: 1,
        extends: [
          // CL,
          FS,
          SS,
          COLOR_RED,
          COLOR_WHITE_MH,
          LED_BLINK,
          MH_POS_ROUND,
          MH_ON,
          BEAMS_WAVE,
          FLOORPAR_RANDOM_BLINK,
        ],
      },
      {
        id: '後奏',
        position: 4 * 60 + 21,
        fade: 1,
        extends: [
          // CL,
          FS,
          SS,
          COLOR_RAINBOW,
          LED_BLINK,
          MH_POS_ROUND,
          MH_BLINK,
          BEAMS_WAVE,
          FLOORPAR_RANDOM_BLINK,
        ],
      },
      {
        id: 'アウトロ',
        position: 4 * 60 + 35,
        fade: 2,
        extends: [
          // CL,
          FS,
          SS,
          COLOR_WHITE,
          LED_ON,
          MH_POS_ROUND,
          FLOORPAR,
        ],
      },
      {
        id: '曲終了',
        position: 4 * 60 + 47,
        fade: 0,
        extends: [GROUND_B, NAGARE_BLUE],
      },
    ],
  },
]
