export enum addrs {
  wash_U_L_DIM = 1,
  wash_U_L_R,
  wash_U_L_G,
  wash_U_L_B,
  wash_U_L_ST = 6,
  wash_U_R_DIM = 7,
  wash_U_R_R,
  wash_U_R_G,
  wash_U_R_B,
  wash_U_R_ST = 12,
  wash_S_L_DIM = 13,
  wash_S_L_R,
  wash_S_L_G,
  wash_S_L_B,
  wash_S_L_ST = 18,
  wash_S_R_DIM = 19,
  wash_S_R_R,
  wash_S_R_G,
  wash_S_R_B,
  wash_S_R_ST = 24,
  wash_SUS_1_DIM = 25,
  wash_SUS_1_R,
  wash_SUS_1_G,
  wash_SUS_1_B,
  wash_SUS_1_ST = 30,
  wash_SUS_2_DIM = 31,
  wash_SUS_2_R,
  wash_SUS_2_G,
  wash_SUS_2_B,
  wash_SUS_2_ST = 36,
  wash_SUS_3_DIM = 37,
  wash_SUS_3_R,
  wash_SUS_3_G,
  wash_SUS_3_B,
  wash_SUS_3_ST = 42,
  wash_SUS_4_DIM = 43,
  wash_SUS_4_R,
  wash_SUS_4_G,
  wash_SUS_4_B,
  wash_SUS_4_ST = 48,
  wash_SUS_5_DIM = 49,
  wash_SUS_5_R,
  wash_SUS_5_G,
  wash_SUS_5_B,
  wash_SUS_5_ST = 54,
  wash_SUS_6_DIM = 55,
  wash_SUS_6_R,
  wash_SUS_6_G,
  wash_SUS_6_B,
  wash_SUS_6_ST = 60,
  SUSFOR,
  SPOT,
}

